# Generated by Django 3.2 on 2021-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cases', models.CharField(max_length=9)),
                ('deaths', models.CharField(max_length=9)),
                ('prob_deaths', models.IntegerField()),
                ('time_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
